test:
	python ../dictionnaryOutput/nonregression.py
run:
	python ./wiktio2xml.py  ../wiktionnaryDump/wiktionary ../wordsList/newList ../dictionnaryOutput/dico

diff:
	xmldiff ../dictionnaryOutput/dictionnaire ../dictionnaryOutput/dictionnaire_1307_0049
