# -*- coding: utf-8 -*-
global lexiques
global temporalites
global registres
global frequences
global typesAllowed
global pays
global regions
global relations
global connotations
global diaintegrations
global genres
global contraintes
global argots

precisionsAllowed = {
    r"anglicisme": r"(Anglicisme)",
    r"germanisme": r"(Germanisme)",
    r"gallicisme": r"(Gallicisme)",
    r"hispanisme": r"(Hispanisme)",
    r"italianisme": r"(Italianisme)",
    r"lusitanisme": r"(Lusitanisme)",
    r"latinisme": r"(Latinisme)",
    r"litt.": r"(Littéraire)",
    r"littéraire": r"(Littéraire)",
    r"rech.": r"(Littéraire)",
    r"littér.": r"(Littéraire)",
    r"littéraire": r"(Littéraire)",
    r"poét.": r"(Poétique)",
    r"poétique": r"(Poétique)",
    r"didact.": r"(Didactique)",
    r"didactique": r"(Didactique)",

    r"épithète": r"(Épithète)",
    r"apposition": r"(Apposition)",
    r"absolument": r"(Absolument)",
    r"ellip": r"(Ellipse)",
    r"au pluriel": r"(Au pluriel)",
    r"au singulier": r"(Au singulier)",
    r"au masculin": r"(Au masculin)",
    r"au féminin": r"(Au féminin)",

    r"arg": r"(Argot)",
    r"argot scolaire": r"(Argot scolaire)",
    r"argot polytechnicien": r"(Argot polytechnicien)",
    r"argot policier": r"(Argot policier)",
    r"argot Internet": r"(Argot Internet)",
    r"argot typographes": r"(Argot typographes)",
    r"argot militaire": r"(Argot militaire)",
    r"argot poilu": r"(Argot poilu)",
    r"argot voleurs": r"(Argot voleurs)",
    r"Argadz": r"(Argadz)",
    r"langage SMS": r"(Langage SMS)",

    r"mélior": r"(Mélioratif)",
    r"péj": r"(Péjoratif)",
    r"péjor": r"(Péjoratif)",
    r"affectueux": r"(Affectueux)", 	
    r"par plaisanterie": r"(Par plaisanterie)",
    r"par plais": r"(Par plaisanterie)",
    r"plais": r"(Par plaisanterie)",
    r"par dérision": r"(Par dérision)", 	
    r"injurieux": r"(Injurieux)",
    r"injur": r"(Injurieux)",
    r"ironique": r"(Ironique)",
    r"iron": r"(Ironique)",

    r"figuré": r"(Figuré)",
    r"idiomatique": r"(Figuré)",
    r"au figuré": r"(Au figuré)",
    r"métaph": r"(Métaphore)",
    r"métaphore": r"(Métaphore)",
    r"sens propre": r"(Sens propre)",
    r"propre": r"(Sens propre)",
    r"par métonymie": r"(Par métonymie)",
    r"métonymie": r"(Par métonymie)",
    r"méton": r"(Par métonymie)",
    r"par hyperbole": r"(Par hyperbole)",
    r"hyperbole": r"(Hyperbole)",
    r"hyperb": r"(Hyperbole)",
    r"exag": r"(Exagération)",
    r"exagération": r"(Exagération)",
    r"par extension": r"(Par extension)",
    r"par ext": r"(Par extension)",
    r"par analogie": r"(Par analogie)",
    r"analogie": r"(Analogie)",
    r"en particulier": r"(En particulier)",
    r"particulier": r"(En particulier)",
    r"partic": r"(En particulier)",
    r"part": r"(En particulier)",
    r"par litote": r"(Par litote)",
    r"par euphémisme": r"(Par euphémisme)",
    r"euphémisme": r"(Par euphémisme)",
    r"euph": r"(Par euphémisme)",
    r"euphém": r"(Par euphémisme)",
    r"spécifiquement": r"(Spécifiquement)",
    r"génériquement": r"(Génériquement)",
    r"spécialement": r"(Spécialement)",
    r"généralement": r"(Généralement)",

    r"Canada": r"(Canada)",
    r"France": r"(France)",
    r"Guinée": r"(Guinée)",
    r"Mali": r"(Mali)",
    r"Belgique": r"(Belgique)",

    r"Bordelais": r"(Bordelaise)",
    r"Acadie": r"(Acadie)",
    r"Auvergne": r"(Auvergne)",
    r"Aquitaine": r"(Aquitaine)",
    r"Antilles": r"(Antilles)",
    r"Anjou": r"(Anjou)",
    r"Bourgogne": r"(Bourgogne)",
    r"Berry": r"(Berry)",
    r"Bretagne": r"(Bretagne)",
    r"Champagne": r"(Champagne)",
    r"Corse": r"(Corse)",
    r"Franche-Comté": r"(Franche-Comté)",
    r"Gaspésie": r"(Gaspésie)",
    r"Gascogne": r"(Gascogne)",
    r"Guadeloupe": r"(Guadeloupe)",
    r"Guyane": r"(Guyane)",
    r"Le Mans": r"(Le Mans)",
    r"Languedoc-Roussillon": r"(Langedoc-Roussillon)",
    r"Limousin": r"(Limousin)",
    r"Lorraine": r"(Lorraine)",
    r"Louisiane": r"(Louisiane)",
    r"Lyonnais": r"(Lyonnais)",
    r"Lorraine": r"(Lorraine)",
    r"Martinique": r"(Martinique)",
    r"Mayotte": r"(Mayotte)",
    r"Midi": r"(Midi)",
    r"Midi toulousain": r"(Midi toulousain)",
    r"Montréal": r"(Montréal)",
    r"Provence": r"(Provence)",
    r"Québec": r"(Québec)",
    r"Quercy": r"(Quercy)",
    r"Normandie": r"(Normandie)",
    r"Nantes": r"(Nantes)",
    r"Picardie": r"(Picardie)",
    r"Poitou": r"(Poitou)",
    r"Polynésie française": r"(Polynésie française)",
    r"Occitanie": r"(Occitanie)",
    r"Provence": r"(Provence)",
    r"Réunion": r"(Réunion)",
    r"Rhône-Alpes": r"(Rhône-Alpes)",
    r"Vosges": r"(Vosges)",
    r"Var": r"(Var)",
    r"Velay": r"(Velay)",

    r"très fam": r"(Très familier)",
    r"fam": r"(Familier)",
    r"dial": r"(Familier)",
    r"oral": r"(Familier)",
    r"informel": r"(Informel)",
    r"populaire": r"(Populaire)",
    r"pop": r"(Populaire)",
    r"vulgaire": r"(Vulgaire)",
    r"vulg": r"(Vulgaire)",
    r"soutenu": r"(Soutenu)",
    r"écrit": r"(Soutenu)",
    r"formel": r"(Soutenu)",
    r"enfantin": r"(Langage enfantin}",

    r"vieilli": r"(Vieilli)",
    r"vx.": r"(Vieilli)",
    r"archaïsme": r"(Archaïsme)",
    r"désuet": r"(Désuet)",
    r"néologisme": r"(Néologisme)",
    r"néol.": r"(Néologisme)",
    r"arch.": r"(Archaïsme)",
    r"archaïsme": r"(Archaïsme)",
    r"anc.": r"(Ancien)",
    r"autref.": r"(Ancien)",
    r"ancien": r"(Ancien)",

    r"comparatif": r"(Comparatif de)",
    r"superlatif": r"(Superlatif de)",
    r"exagératif": r"(Exagératif de)",
    
    r"ébauche-déf": r"Définition manquante ou à compléter",

    r"courant": r"(Courant)",
    r"cour.": r"(Courant)",
    r"peu usité": r"(Peu usité)",
    r"rare": r"(Rare)",
    r"rar": r"(Rare)",
    r"très rare": r"(Très rare)",
    r"extrêmement rare": r"(Extrêmement rare)",
    r"hapax": r"(Hapax)",
    r"peu attesté": r"(Peu attesté)",
    r"plus rare": r"(Plus rare}",
    r"moins courant": r"(Moins courant}",
    r"beaucoup moins courant": r"(Beaucoup moins courant}",
    r"plus courant": r"(Plus courant}",
    r"beaucoup plus courant": r"(Beaucoup plus courant}",

    r"acoustique": r"(Acoustique)",
    r"administration": r"(Administration)",
    r"aéronautique": r"(Aéronautique)",
    r"agriculture": r"(Agriculture)",
    r"agronomie": r"(Agronomie)",
    r"aïkido": r"(Aïkido)",
    r"alchimie": r"(Alchimie)",
    r"algèbre": r"(Algèbre)",
    r"alpinisme": r"(Alpinisme)",
    r"analyse": r"(Analyse)",
    r"anatomie": r"(Anatomie)",
    r"anthropologie": r"(Anthropologie)",
    r"antiquité": r"(Antiquité)",
    r"apiculture": r"(Apiculture)",
    r"arboriculture": r"(Arboriculture)",
    r"archéologie": r"(Archéologie)",
    r"architecture": r"(Architecture)",
    r"Argadz": r"(Argadz)",
    r"armement": r"(Armement)",
    r"arts": r"(Arts)",
    r"arts martiaux": r"(Arts martiaux)",
    r"assurance": r"(Assurance)",
    r"astrologie": r"(Astrologie)",
    r"astronautique": r"(Astronautique)",
    r"astronomie": r"(Astronomie)",
    r"astrophysique": r"(Astrophysique)",
    r"athlétisme": r"(Athlétisme)",
    r"audiovisuel": r"(Audiovisuel)",
    r"automatique": r"(Automatique)",
    r"automobile": r"(Automobile)",
    r"aviation": r"(Aviation)",
    r"baby-foot": r"(Baby-foot)",
    r"bactériologie": r"(Bactériologie)",
    r"badminton": r"(Badminton)",
    r"base de données": r"(Base de données)",
    r"baseball": r"(Baseball)",
    r"basket-ball": r"(Basket-ball)",
    r"BD": r"(BD)",
    r"beaux-arts": r"(Beaux-arts)",
    r"bibliothéconomie": r"(Bibliothéconomie)",
    r"bijouterie": r"(Bijouterie)",
    r"billard": r"(Billard)",
    r"biochimie": r"(Biochimie)",
    r"biogéographie": r"(Biogéographie)",
    r"biologie": r"(Biologie)",
    r"biophysique": r"(Biophysique)",
    r"bonsaï": r"(Bonsaï)",
    r"botanique": r"(Botanique)",
    r"boucherie": r"(Boucherie)",
    r"bouddhisme": r"(Bouddhisme)",
    r"bourrellerie": r"(Bourrellerie)",
    r"bowling": r"(Bowling)",
    r"boxe": r"(Boxe)",
    r"bridge": r"(Bridge)",
    r"calendrier": r"(Calendrier)",
    r"calligraphie": r"(Calligraphie)",
    r"canoë-kayak": r"(Canoë-kayak)",
    r"capoeira": r"(Capoeira)",
    r"cartes": r"(Cartes)",
    r"cartographie": r"(Cartographie)",
    r"caséologie": r"(Caséologie)",
    r"catch": r"(Catch)",
    r"CB": r"(CB)",
    r"céramique": r"(Céramique)",
    r"charpenterie": r"(Charpenterie)",
    r"charronnerie": r"(Charronnerie)",
    r"chasse": r"(Chasse)",
    r"chimie": r"(Chimie)",
    r"chiromancie": r"(Chiromancie)",
    r"chirurgie": r"(Chirurgie)",
    r"christianisme": r"(Christianisme)",
    r"chronologie": r"(Chronologie)",
    r"cinéma": r"(Cinéma)",
    r"cirque": r"(Cirque)",
    r"climatologie": r"(Climatologie)",
    r"coiffure": r"(Coiffure)",
    r"colorimétrie": r"(Colorimétrie)",
    r"commerce": r"(Commerce)",
    r"comptabilité": r"(Comptabilité)",
    r"construction": r"(Construction)",
    r"copropriété": r"(Copropriété)",
    r"cordonnerie": r"(Cordonnerie)",
    r"cosmétologie": r"(Cosmétologie)",
    r"couche application": r"(Couche application)",
    r"couche liaison": r"(Couche liaison)",
    r"couche physique": r"(Couche physique)",
    r"couche présentation": r"(Couche présentation)",
    r"couche réseau": r"(Couche réseau)",
    r"couche session": r"(Couche session)",
    r"couche transport": r"(Couche transport)",
    r"course à pied": r"(Course à pied)",
    r"couture": r"(Couture)",
    r"cricket": r"(Cricket)",
    r"cryptographie": r"(Cryptographie)",
    r"cryptomonnaie": r"(Cryptomonnaie)",
    r"cuisine": r"(Cuisine)",
    r"cyclisme": r"(Cyclisme)",
    r"dames": r"(Dames)",
    r"danse": r"(Danse)",
    r"dentisterie": r"(Dentisterie)",
    r"dermatologie": r"(Dermatologie)", 
    r"dessin": r"(Dessin)",
    r"didactique": r"(Didactique)",
    r"diplomatie": r"(Diplomatie)",
    r"drogue": r"(Drogue)",
    r"droit": r"(Droit)",
    r"échafaudage": r"(Échafaudage)",
    r"échecs": r"(Échecs)",
    r"écologie": r"(Écologie)",
    r"économie": r"(Économie)",
    r"édition": r"(Édition)",
    r"éducation": r"(Éducation)",
    r"électoraux": r"(Électoraux)",
    r"électricité": r"(Électricité)",
    r"électronique": r"(Électronique)",
    r"électrotechnique": r"(Électrotechnique)",
    r"élevage": r"(Élevage)",
    r"embryologie": r"(Embryologie)",
    r"entomologie": r"(Entomologie)",
    r"équitation": r"(Équitation)",
    r"escrime": r"(Escrime)",
    r"ethnobiologie": r"(Ethnobiologie)",
    r"ethnologie": r"(Ethnologie)",
    r"famille": r"(Famille)",
    r"fantastique": r"(Fantastique)",
    r"fauconnerie": r"(Fauconnerie)",
    r"ferroviaire": r"(Ferroviaire)",
    r"finance": r"(Finance)",
    r"fiscalité": r"(Fiscalité)",
    r"fontainerie": r"(Fontainerie)",
    r"football": r"(Football)",
    r"foresterie": r"(Foresterie)",
    r"franc-maçonnerie": r"(Franc-maçonnerie)",
    r"généalogie": r"(Généalogie)",
    r"génétique": r"(Génétique)",
    r"géographie": r"(Géographie)",
    r"géologie": r"(Géologie)",
    r"géomatique": r"(Géomatique)",
    r"géométrie": r"(Géométrie)", 
    r"géophysique": r"(Géophysique)",
    r"géostatistique": r"(Géostatistique)",
    r"glaciologie": r"(Glaciologie)",
    r"golf": r"(Golf)",
    r"grammaire": r"(Grammaire)",
    r"gravure": r"(Gravure)",
    r"gymnastique": r"(Gymnastique)",
    r"handball": r"(Handball)",
    r"handisport": r"(Handisport)",
    r"héraldique": r"(Héraldique)", 
    r"hindouisme": r"(Hindouisme)",
    r"hippisme": r"(Hippisme)",
    r"hippologie": r"(Hippologie)",
    r"histoire": r"(Histoire)",
    r"histologie": r"(Histologie)",
    r"hockey": r"(Hockey)",
    r"horlogerie": r"(Horlogerie)",
    r"horticulture": r"(Horticulture)",
    r"hydraulique": r"(Hydraulique)",
    r"hydrobiologie": r"(Hydrobiologie)",
    r"hydrologie": r"(Hydrologie)",
    r"hygiène": r"(Hygiène)",
    r"ichtyologie": r"(Ichtyologie)",
    r"illégalité": r"(Illégalité)",
    r"imprimerie": r"(Imprimerie)",
    r"industrie": r"(Industrie)",
    r"infographie": r"(Infographie)",
    r"informatique": r"(Informatique)",
    r"intelligence artificielle": r"(Intelligence artificielle)",
    r"internet": r"(Internet)",
    r"islam": r"(Islam)",
    r"jardinage": r"(Jardinage)",
    r"jazz": r"(Jazz)",
    r"jeu de go": r"(Jeu de go)",
    r"jeu de paume": r"(Jeu de paume)",
    r"jeux": r"(Jeux)",
    r"jeux vidéo": r"(Jeux vidéo)",
    r"jonglerie": r"(Jonglerie)",
    r"journalisme": r"(Journalisme)",
    r"judaïsme": r"(Judaïsme)",
    r"judo": r"(Judo)",
    r"justice": r"(Justice)",
    r"karaté": r"(Karaté)",
    r"langage Java": r"(Langage Java)",
    r"législation": r"(Législation)",
    r"lexicographie": r"(Lexicographie)",
    r"LGBT": r"(LGBT)",
    r"linguistique": r"(Linguistique)",
    r"littérature": r"(Littérature)",
    r"liturgie": r"(Liturgie)",
    r"livre": r"(Livre)",
    r"logique": r"(Logique)",
    r"logistique": r"(Logistique)",
    r"loisirs": r"(Loisirs)",
    r"lutherie": r"(Lutherie)",
    r"maçonnerie": r"(Maçonnerie)",
    r"magnétisme": r"(Magnétisme)",
    r"mah-jong": r"(Mah-jong)",
    r"maintenance": r"(Maintenance)",
    r"marbrerie": r"(Marbrerie)",
    r"maréchalerie": r"(Maréchalerie)",
    r"marine": r"(Marine)",
    r"maroquinerie": r"(Maroquinerie)",
    r"mathématiques": r"(Mathématiques)",
    r"mécanique": r"(Mécanique)",
    r"médecine": r"(Médecine)",
    r"médecine non conv": r"(Médecine non conv)",
    r"médecine vétérinaire": r"(Médecine vétérinaire)",
    r"média": r"(Média)",
    r"menuiserie": r"(Menuiserie)", 
    r"mercatique": r"(Mercatique)",
    r"metal": r"(Metal)",
    r"métallurgie": r"(Métallurgie)",
    r"météorologie": r"(Météorologie)",
    r"métrologie": r"(Métrologie)",
    r"meunerie": r"(Meunerie)",
    r"microbiologie": r"(Microbiologie)",
    r"militaire": r"(Militaire)",
    r"minéralogie": r"(Minéralogie)",
    r"miroiterie": r"(Miroiterie)",
    r"monarchie": r"(Monarchie)",
    r"morphologie végétale": r"(Morphologie végétale)",
    r"motocyclisme": r"(Motocyclisme)",
    r"Moyen Âge": r"(Moyen Âge)",
    r"muscle": r"(Muscle)",
    r"musculation": r"(Musculation)",
    r"muséologie": r"(Muséologie)",
    r"musique": r"(Musique)",
    r"mycologie": r"(Mycologie)",
    r"mythologie": r"(Mythologie)",
    r"narratologie": r"(Narratologie)",
    r"natation": r"(Natation)",
    r"navigation": r"(Navigation)",
    r"neurologie": r"(Neurologie)",
    r"noblesse": r"(Noblesse)",
    r"nosologie": r"(Nosologie)",
    r"novlangue": r"(Novlangue)",
    r"nucléaire": r"(Nucléaire)",
    r"numismatique": r"(Numismatique)",
    r"nutrition": r"(Nutrition)",
    r"occultisme": r"(Occultisme)",
    r"océanographie": r"(Océanographie)",
    r"œnologie": r"(Œnologie)",
    r"optimisation": r"(Optimisation)",
    r"optique": r"(Optique)",
    r"orgues": r"(Orgues)",
    r"ornement": r"(Ornement)",
    r"ornithologie": r"(Ornithologie)",
    r"paléographie": r"(Paléographie)",
    r"paléontologie": r"(Paléontologie)",
    r"papeterie": r"(Papeterie)",
    r"patinage": r"(Patinage)",
    r"pâtisserie": r"(Pâtisserie)",
    r"pêche": r"(Pêche)",
    r"pédologie": r"(Pédologie)",
    r"peinture": r"(Peinture)",
    r"pelote": r"(Pelote)",
    r"pétanque": r"(Pétanque)",
    r"pétrochimie": r"(Pétrochimie)",
    r"pharmacologie": r"(Pharmacologie)",
    r"phénologie": r"(Phénologie)",
    r"phénoménologie": r"(Phénoménologie)",
    r"philatélie": r"(Philatélie)",
    r"philosophie": r"(Philosophie)",
    r"phonétique": r"(Phonétique)",
    r"phonologie": r"(Phonologie)",
    r"photographie": r"(Photographie)",
    r"physiologie": r"(Physiologie)",
    r"physique": r"(Physique)",
    r"phytosociologie": r"(Phytosociologie)",
    r"planche à neige": r"(Planche à neige)",
    r"planche à roulettes": r"(Planche à roulettes)",
    r"plomberie": r"(Plomberie)",
    r"plongée": r"(Plongée)",
    r"poésie": r"(Poésie)",
    r"poker": r"(Poker)",
    r"police": r"(Police)",
    r"politique": r"(Politique)",
    r"préhistoire": r"(Préhistoire)",
    r"prestidigitation": r"(Prestidigitation)",
    r"probabilités": r"(Probabilités)",
    r"programmation": r"(Programmation)",
    r"programmation orientée objet": r"(Programmation orientée objet)",
    r"propriété": r"(Propriété)",
    r"psychanalyse": r"(Psychanalyse)",
    r"psychiatrie": r"(Psychiatrie)",
    r"psychologie": r"(Psychologie)",
    r"pyrotechnie": r"(Pyrotechnie)",
    r"raffinage": r"(Raffinage)",
    r"regex": r"(Regex)",
    r"relations internationales": r"(Relations internationales)",
    r"religion": r"(Religion)",
    r"reliure": r"(Reliure)",
    r"renseignement": r"(Renseignement)",
    r"reproduction": r"(Reproduction)",
    r"réseaux informatiques": r"(Réseaux informatiques)",
    r"rhétorique": r"(Rhétorique)",
    r"robotique": r"(Robotique)",
    r"rugby": r"(Rugby)",
    r"saliculture": r"(Saliculture)",
    r"saut en hauteur": r"(Saut en hauteur)",
    r"science-fiction": r"(Science-fiction)",
    r"sciences": r"(Sciences)",
    r"Scrabble": r"(Scrabble)",
    r"sculpture": r"(Sculpture)",
    r"serrurerie": r"(Serrurerie)",
    r"sexualité": r"(Sexualité)",
    r"sidérurgie": r"(Sidérurgie)",
    r"ski alpin": r"(Ski alpin)",
    r"ski de fond": r"(Ski de fond)",
    r"snowboard": r"(Snowboard)",
    r"socialisme": r"(Socialisme)",
    r"sociolinguistique": r"(Sociolinguistique)",
    r"sociologie": r"(Sociologie)",
    r"sport": r"(Sport)",
    r"squelette": r"(Squelette)",
    r"statistiques": r"(Statistiques)",
    r"stéréochimie": r"(Stéréochimie)",
    r"stéréotomie": r"(Stéréotomie)",
    r"stéréotype": r"(Stéréotype)",
    r"surf": r"(Surf)",
    r"sylviculture": r"(Sylviculture)",
    r"taille de pierre": r"(Taille de pierre)",
    r"tauromachie": r"(Tauromachie)",
    r"technique": r"(Technique)",
    r"technologie": r"(Technologie)",
    r"télécommunications": r"(Télécommunications)",
    r"téléinformatique": r"(Téléinformatique)",
    r"téléphonie": r"(Téléphonie)",
    r"tennis": r"(Tennis)",
    r"tennis de table": r"(Tennis de table)",
    r"tératologie": r"(Tératologie)",
    r"textile": r"(Textile)",
    r"théâtre": r"(Théâtre)",
    r"théologie": r"(Théologie)",
    r"théorie des graphes": r"(Théorie des graphes)",
    r"thermodynamique": r"(Thermodynamique)",
    r"tonnellerie": r"(Tonnellerie)",
    r"topographie": r"(Topographie)",
    r"topologie": r"(Topologie)",
    r"toponymie": r"(Toponymie)",
    r"tourisme": r"(Tourisme)",
    r"transport": r"(Transport)",
    r"travail": r"(Travail)",
    r"triathlon": r"(Triathlon)",
    r"typographie": r"(Typographie)",
    r"ufologie": r"(Ufologie)",
    r"urbanisme": r"(Urbanisme)",
    r"usinage": r"(Usinage)",
    r"vaudou": r"(Vaudou)",
    r"versification": r"(Versification)",
    r"vexillologie": r"(Vexillologie)",
    r"virologie": r"(Virologie)",
    r"viticulture": r"(Viticulture)",
    r"vitrerie": r"(Vitrerie)",
    r"volley-ball": r"(Volley-ball)",
    r"wiki": r"(Wiki)",
    r"yoga": r"(Yoga)",
    r"zoologie": r"(Zoologie)"
}

typesAllowed = [
    r"adjectif",
    r"adjectif démonstratif",
    r"adjectif exclamatif",
    r"adjectif indéfini",
    r"adjectif interrogatif",
    r"adjectif numéral",
    r"adjectif possessif",
    r"adverbe",
    r"adverbe indéfini",
    r"adverbe interrogatif",
    r"dverbe pronominal",
    r"adverbe relatif",
    r"article défini",
    r"article indéfini",
    r"article",
    r"conjonction de coordination",
    r"déterminant",
    r"nom",
    r"nom commun",
    r"préposition",
    r"pronom démonstratif",
    r"pronom indéfini",
    r"pronom interrogatif",
    r"ronom personnel",
    r"pronom possessif",
    r"pronom relatif",
    r"pronom",
    r"pronom-adjectif",
    r"verbe" 
]
